##Add Code

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -7,7 +7,7 @@ workflows:
       android_signing:
         - Testing App
       groups:
-        - email
+        - google_play
       vars:
         PACKAGE_NAME: "com.example.testingapplication"
     triggering:
@@ -24,7 +24,20 @@ workflows:
           echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
       - name: Build Android release
         script: |
-          ./gradlew assembleDebug
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z LATEST_BUILD_NUMBER ]; then
+      # fallback in case no build number was found from Google Play.
+      # Alternatively, you can `exit 1` to fail the build
+      # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+      # of times this workflow has been built
+         UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+         else
+         UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+         fi
+         cd android
+         ./gradlew bundleRelease \
+         -PversionCode=$UPDATED_BUILD_NUMBER \
+         -PversionName=1.0.$UPDATED_BUILD_NUMBER
     artifacts:
       - app/build/outputs/**/*.aab
     publishing:
